name: test

on:
  pull_request: ~
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello"
      - run: ls
      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: "**/junit-example.xml"
      - run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/check-runs \
            -d '{"name":"mighty_readme","head_sha":"${{ github.event.pull_request.base.sha }}","status":"in_progress","started_at":"2018-05-04T01:14:52Z","output":{"title":"Mighty Readme report","summary":"","text":""}}'
