name: test

on:
  pull_request:
  push:
    branches:
      - main

# Cancel previous runs only on pull requests
concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ !!github.head_ref }}

permissions:
  contents: read

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: v1v/otel-upload-test-artifact-action@v2
        if: always()
        with:
          jobName: "macos"
          stepName: "Run test"
          path: "README.md"
          type: "junit"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: README.md
  post-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test-results
          path: .
      - name: Print test results
        run: |
         ls
         cat README.md
